### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by guy426** [c0d3z3r0/i2ite#1]
Which ITE chip have you try?
I can't get any response from it8585e and it8512e.
How you get i2c slave address ?
It is software configurable from ec bios.

**Comment by c0d3z3r0** [comment]
The address is fixed and not configurable. The firmware is able to disable the DBGR interface early. That might be the case here.
Can you tell me a bit more about your setup, please?
- What board(s)?
- How exactly did you connect the FTDI to the board?

My boards both have an IT5570E

**Comment by guy426** [comment]
My motherboards are Asus X555LA (IT8585E) and Asus UX31 (IT8512E)
I connect FTDI interface to EC pins called SMBCLK0 and SMBDAT0.
In EC datasheet (IT8585E not found, but IT5576E is very similar)  there is no reference to any i2c fixed address.

**Comment by guy426** [comment]
DBGR/EPP and DBGR/SMB are default disabled and there are no reason to ec firmware to enable it.
DBGR/EPP can be enable to strap pin KSI4 and KSI5 to ground at reset.
Is there a similar mode to enable DBGR/SMB ?

**Comment by c0d3z3r0** [comment]
> My motherboards are Asus X555LA (IT8585E) and Asus UX31 (IT8512E) I connect FTDI interface to EC pins called SMBCLK0 and SMBDAT0.

Sounds good. Did you connect D1,D2 on the FTDI like shown in the readme?

Did you try connecting when the board is off or on? AC attached? I checked both boards. The EC is only powered when either 1) the system is on or 2) the AC is attached.

> In EC datasheet (IT8585E not found, but IT5576E is very similar) there is no reference to any i2c fixed address.

It's not documented

> DBGR/EPP and DBGR/SMB are default disabled and there are no reason to ec firmware to enable it. DBGR/EPP can be enable to strap pin KSI4 and KSI5 to ground at reset. Is there a similar mode to enable DBGR/SMB ?

DBGR/SMB is default enabled

**Comment by guy426** [comment]
Yes, i connect FTDI as you show and i try with AC attached and system power on. 
I also try with another interface based on cp2112 but same results, i can read BQ charge chip but nothing come from EC.
I also try with Asus K56CM motherboard with IT8517E. Some results.
Scanning i2c address display only BQ address.
I think that DBGR/SMB is not default enable.

**Comment by c0d3z3r0** [comment]
> Scanning i2c address display only BQ address.

ah, that's a good hint - the DBGR adresses should definitely show up when scanning

> I think that DBGR/SMB is not default enable.

I'm 99% sure there is no difference between the ECs and it's default enabled. On ECs with integrated flash ("eFlash") DBGR/SMB is used for initial flashing.

Hmm, I guess the firmware is disabling debug access. Ok, before I dig into the EC fw... let's try this:

1) detach AC
2) pull MOSI (pin 5) of the SPI flash to GND
3) press power button once (to discharge any caps, so the EC is surely reset)
4) attach EC
5) test i2ite

Do ***NOT*** power on the system during this test! This *could* damage the PCH.

The idea behind this is that the EC can't load the firmware and thus, DBGR/SMB should not get disabled. If that works, I can find a way to prevent the FW from doing that. If it doesn't work, there is another problem.

**Comment by guy426** [comment]
Test made on IT8585E (internal flash) and IT8517E (external flash) nothing
happened.
I think a fundamental role is in hardware strap pin.
Can you measure KSI1 KSI2 KSI4 KSI5 pin on your motherboard ?

Il giorno ven 7 gen 2022 alle ore 21:52 Michael Niewöhner <
***@***.***> ha scritto:

**Comment by c0d3z3r0** [comment]
all KSI*/KSO* are NC on my board with the keyboard disconnected. These pins are not relevant for DBGR/SMB, only for DBGR/EPP.

What error exactly do you get, when trying to connect? Do you run as user or root? If user, does your FTDI interface have the right permissions set?

**Comment by c0d3z3r0** [comment]
Something I just noticed: IT5570/IT5576, IT8987 list DGBR/SMB explicitly, while e.g. IT8512E, IT8570E do not. *Maybe* they simply don't support DBGR/SMB :S

**Comment by guy426** [comment]
I'm afraid the last you said, no datasheet of it85xx series mentions DBGR/SMB....
I haven't other motherboard to try.
Thanks for your time.

**Comment by c0d3z3r0** [comment]
Thank you, too!

**Comment by tommie** [comment]
For anyone coming here about IT8586E...

DBGR SMB is supported, but you have to power up VCC (pin 11), not just VSTBY. Both are required for it to respond.

**Edit** This was in a Lenovo L470. It seems VCC is only required sometimes. Once the EC is running (it starts pinging something on the SMBus) the VCC doesn't seem needed anymore. Perhaps it's only for the reset logic. The +3VL on that board (tied to EC VCC) draws 170 mA, and it cross-feeds 2.2 V into +3VS (which is EC VSTBY, which normally draws like 10 mA.) Power sequence might be important. I had more luck connecting VCC first and then VSTBY.
