### ISSUE TITLE
what binary are you "reverese engineering" here? (help with JTAG instrumentation)

### ISSUE THREAD

**Issue by Mis012** [c0d3z3r0/i2ite#2]
Hi,
I've recently gotten back to poking at it8225e, and I've managed to successfully use i2ec to interact with the JTAG bridge mentioned in the it81202 datasheet to the extent of clocking out 3d 06 00 10 with the IDCODE instruction.
I have further managed to find this file: https://github.com/andestech/nds-openocd/blob/ast-v5_1_0-branch/src/jtag/aice/aice_vendor.c
which seems to add support for directly using JTAG on andes cores (as opposed to targeting their usb adapter like the drivers which they actually upstreamed to OpenOCD), and it would seem that this is precisely the JTAG interface exposed by the bridge (at least for the it81202 for which I have a datasheet) - additionally, that same OpenOCD fork also mentions that `0x1000063d` is the JTAG ID for an nds32 CPU core, confirming that ite8225 is indeed similar to it81202 in that way.

I have however been unable to get a satisfactory result from my attempts at manually reading a word using the ACCESS_MEM_W instruction, which using 64 bits for data doesn't even bring the question of how to handle clocking in/out 33 bits by sending out 8 bits at a time.

I have failed to locate the official software from ITE for the purposes of reverse enginnering, but seeing as you're mentioning reverse engineering I gather you may be in possesion of said software and could help me with writing an OpenOCD driver for this peculiar interface, such that one could use andes' OpenOCD fork to debug the core over i2ec or d2ec

**Comment by c0d3z3r0** [comment]
This is not about reverse engineering but debugging. Sure, one can use it to help RE of course.
IT81202 is different, since it supports JTAG (which other ITE ECs don't), as you already found out.
That EC uses 24 bit addressing IIRC, so i2ite might not work at all in the current form.
I have no experience with IT81202 though, so I can't help there, sorry :/

**Comment by Mis012** [comment]
my ITE EC is IT8225E, and it seems to have that jtag bridge in it's address space at the same place as it81202 (which I do not have, but I have a datasheet for it unlike the IT8225E)

i2ite not working on it81202 might make sense, since it seems that it describes a different method for debugging over i2c (no pin stimulation needed, different commands) but I have i2ec over the LPC connection, which is quite a bit more convenient than using an external debugger.

I saw that you mentioned IT5570 works with i2ite, and I have somebody who has a qcom SoC laptop using IT5571 where for some bizzare reason instead of the espi, the OEM decided to use one i2c slave for i2c-hid for keyboard and one i2c slave for their stupid vendor defined protocol - so that's where I would like to see this tool work (sadly might need some fixing to remove ugly ftdi specific stuff in favor of /dev/i2c and gpiod - is there no Linux kernel driver to expose the ftdi thing's interfaces properly?)

---

as for the RE, my question was whether you have access to the program from ITE which implements the JTAG stuff, so that I could RE how that program uses the JTAG

**Comment by c0d3z3r0** [comment]
> my ITE EC is IT8225E, and it seems to have that jtag bridge in it's address space at the same place as it81202 (which I do not have, but I have a datasheet for it unlike the IT8225E)

No idea tbh, as I don't have the IT8225E datasheet either. Maybe write ITE and ask for it?

> i2ite not working on it81202 might make sense, since it seems that it describes a different method for debugging over i2c (no pin stimulation needed, different commands)

The pin toggling activation wave is still needed on IT81202, it's just not documented (ask ITE for more details). There is an addtional one for enabling DBGR on the USB pins. Check out Google's iteflash code for the wave pattern: https://chromium.googlesource.com/chromiumos/platform/ec/+/master/util/iteflash.c

> but I have i2ec over the LPC connection, which is quite a bit more convenient than using an external debugger.

Well, both interfaces are there to be used depending on your needs. It's not really about "convenience". I2EC might be more convenient for your specific use case. When you need to debug without a running OS, then you'd be better of with the external method.

> I saw that you mentioned IT5570 works with i2ite, and I have somebody who has a qcom SoC laptop using IT5571 where for some bizzare reason instead of the espi, the OEM decided to use one i2c slave for i2c-hid for keyboard and one i2c slave for their stupid vendor defined protocol - so that's where I would like to see this tool work 

You won't be able to use the main i2c interface since debugger would impact any ongoing host communication. However, using DBGR on the keyboard i2c interface might work (with keyboard detached).

> (sadly might need some fixing to remove ugly ftdi specific stuff in favor of /dev/i2c and gpiod - 

"Fixing" would imply that my tool is broken. It might not fit your use case but it's not broken...

> is there no Linux kernel driver to expose the ftdi thing's interfaces properly?)

Nope.

> as for the RE, my question was whether you have access to the program from ITE which implements the JTAG stuff, so that I could RE how that program uses the JTAG

No, sorry, I don't have it. Maybe ask ITE for the tool, but I doubt that they will hand it out without NDA.
Check out section 7.18 of the IT81202 datasheet, which shows the JTAG controller. Looks like it's as easy as writing these registers through I2EC.

**Comment by Mis012** [comment]
impacting host communication is definitely my plan, so that much is fine :P
the host is Linux in all of my cases, and I would fully intend to either port cros-ec or to inject a stub piece of code that forwards the interrupts to the host, as opposed to writing a Linux kernel driver for the NIH protocol of any particular vendor (or all of them really)

As for "fixing", in my humble opinion there is no good reason for this tool to depend on hw by a single vendor when Linux already has /dev/i2c and gpiod, and as an i2c/gpio controller the ftdi chip should just have a kernel driver which exposes the functionality through the standardized subsystems. I guess Windows doesn't necessarily allow for a sane approach, but eh

well, writing those JTAG registers is not really the issue, I even managed to get the IDCODE out... the issue at hand is that they clock in/out one byte at a time, and I have no idea whatsoever how that behaves for instructions which require clocking in/out something like 33 bits... also writing a jtag driver for OpenOCD doesn't seem trivial, so I should probably find someone to explain that to me (the docs don't seem to have a section on it)

**Comment by c0d3z3r0** [comment]
> impacting host communication is definitely my plan, so that much is fine :P the host is Linux in all of my cases, and I would fully intend to either port cros-ec or to inject a stub piece of code that forwards the interrupts to the host, as opposed to writing a Linux kernel driver for the NIH protocol of any particular vendor (or all of them really)
> 
> As for "fixing", in my humble opinion there is no good reason for this tool to depend on hw by a single vendor when Linux already has /dev/i2c and gpiod, and as an i2c/gpio controller the ftdi chip should just have a kernel driver which exposes the functionality through the standardized subsystems. I guess Windows doesn't necessarily allow for a sane approach, but eh

The "good reason" is that there is no upstream driver. Also, this tool is open source... I don't see a pull request from you making it generic, so what are you complaining about wtf

> 
> well, writing those JTAG registers is not really the issue, I even managed to get the IDCODE out... the issue at hand is that they clock in/out one byte at a time, and I have no idea whatsoever how that behaves for instructions which require clocking in/out something like 33 bits... also writing a jtag driver for OpenOCD doesn't seem trivial, so I should probably find someone to explain that to me (the docs don't seem to have a section on it)
